# Generated by Django 5.2.7 on 2025-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_remove_order_contact_phone_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_sale_id',
            field=models.CharField(blank=True, help_text='ID de la venta en el microservicio de Ventas', max_length=100, null=True),
        ),
    ]
