# Generated by Django 5.2.7 on 2025-10-16 20:39

import storefront.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_productimage_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=storefront.models.ProductImage.product_media_upload_to),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=storefront.models.ProductImage.product_media_upload_to),
        ),
    ]
