# Generated by Django 5.2.7 on 2025-10-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
