# Generated by Django 5.2.7 on 2025-10-16 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_claim'),
        ('storefront', '0004_remove_order_contact_phone_remove_order_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'branch')},
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['date', 'type'], name='dashboard_f_date_d7efa6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity'], name='dashboard_i_quantit_54d2fb_idx'),
        ),
    ]
