# Generated by Django 5.2.7 on 2025-10-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='historialinventario',
            options={'managed': False, 'verbose_name': 'Historial de Inventario', 'verbose_name_plural': 'Historiales de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False, 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
