# Generated by Django 5.2.7 on 2025-10-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_add_historial_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoCupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField()),
                ('fecha_uso', models.DateTimeField()),
            ],
            options={
                'db_table': 'UsoCupones',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.AlterModelOptions(
            name='cupon',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='ReporteMensualProductos',
        ),
    ]
