# Generated by Django 5.2.7 on 2025-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_usocupon_delete_auditoria_alter_cupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=50, unique=True, blank=True),
        ),
    ]
