# Generated by Django 5.2.7 on 2025-10-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': False, 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AlterModelOptions(
            name='devolucion',
            options={'managed': False, 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False, 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
