# Generated by Django 5.2.7 on 2025-10-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Cliente'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('SUPPORT', 'Soporte')], default='CUSTOMER', max_length=10, verbose_name='rol'),
        ),
    ]
