# Generated by Django 5.2.7 on 2025-10-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
